ALTER TABLE `faq` ADD `profile_id` INT NOT NULL AFTER `id`;

ALTER TABLE `faq` ADD FOREIGN KEY (`profile_id`) REFERENCES `user_profiles`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;


INSERT INTO `faq` (`profile_id`, `questions`, `answers`) VALUES
(2, 'How do I sign up?', '<p>\r\n\r\n\r\n	\r\n	\r\n	\r\n	\r\n	</p><p>To\r\nsign up, please download the Seazoned app from the <u><a href="https://itunes.apple.com/us/app/plowz-and-mowz/id728659261?mt=8" rel="nofollow" target="_blank">iTunes\r\nApp Store</a></u>&nbsp;or <u><a href="https://play.google.com/store/apps/details?id=com.plowz.app" rel="nofollow" target="_blank">Google\r\nPlay Store</a></u>,\r\nand enter your information into the app. Or register through our\r\nwebsite via <a href="http://www.seazoned.com" rel="nofollow" target="_blank">www.seazoned.com</a></p>\r\n\r\n<br><p></p>'),
(2, 'How is the price determined?', '<p>\r\n\r\n\r\n	\r\n	\r\n	\r\n	\r\n	</p><p>Because\r\nwe provide freelance work, we allow our providers to be able to set\r\ntheir own pricing based on job specifications. \r\n</p>\r\n\r\n<br><p></p>'),
(2, 'Will I know the cost up front?', '<p>\r\n\r\n\r\n	\r\n	\r\n	\r\n	\r\n	</p><p>Of\r\ncourse, once registered you will have access to view and compare\r\npricing for every service provider in your area.</p>\r\n\r\n<br><p></p>'),
(2, 'Does Seazoned offer recurring service? Or do I have to keep ordering each time?', '<p>\r\n\r\n\r\n	\r\n	\r\n	\r\n	\r\n	</p><p>Yes\r\nwe offer recurring services. Should you select a recurring service,\r\nthe provider will be notified each time the service needs to be\r\nrepeated. You will not be charged until the job has been completed.</p>\r\n\r\n<br><p></p>'),
(2, 'Is it possible to schedule a Seazoned service for someone else? Or have multiple properties needing to be serviced?', '<p>Yes!\r\nPlease check to make sure providers are available in the area you’d\r\nlike serviced. You can enter multiple addresses into the app/website.\r\nWhen you schedule your next service simply select the address you\r\nwant serviced. \r\n\r\n\r\n<br></p>'),
(2, 'What does Seazoned services include?', '<p><b>Pool\r\nCleaning and Upkeep</b>:\r\nbasic pool maintenance, brushing sides, balancing chemicals,\r\nskimming, removing normal day to day debris, back wash as needed (if\r\nrecurring service), pool pump basket cleanout.\r\n</p><p><br>\r\n</p>\r\n<p><b>Mowing\r\nand Edging:</b>\r\nbasic mowing, trimming, and blowing of clippings.</p>\r\n<p><br>\r\n</p>\r\n<p><b>Aeration</b>:\r\nBasic aeration of lawn with Aeration machine.</p>\r\n<p><br>\r\n</p>\r\n<p><b>Lawn\r\nTreatment: </b>seasonal\r\nlawn treatments depending on geographical area and need.</p>\r\n<p><br>\r\n</p>\r\n<p><b>Leaf\r\nRemoval</b>:\r\nLeafs are gathered and removed.</p>\r\n<p><br>\r\n</p>\r\n<p><b>Snow\r\nRemoval</b>:\r\nbasic snow plowing of a driveway is included along with any\r\nadditional walkways and or entry ways you have selected. This does\r\nnot include salting or snow removal of sidewalks. (We recommend you\r\nuse snow stakes to locate your driveway in order to prevent damage to\r\nyour property). If you do not stake your driveway, we (Seazoned LLC)\r\nand the providers will not be liable for any damage done. \r\n</p>\r\n<p><br>\r\n</p>\r\n<p><b>Sprinkler\r\nWinterizing:</b>\r\nBasic blowout of sprinkler pipes and winterizing. \r\n</p>\r\n\r\n<br><p></p>'),
(2, 'What happens in the event of inclement weather?', '<p>In\r\nthe event of inclement weather the provider may push the job back as\r\nmuch as 72 hrs. If they are unable to complete your job within the 72\r\nhr time frame, we will refund you your money.  You will be contacted\r\nif the provider is unable to complete the work because of inclement\r\nweather. It is important that the providers complete the work on\r\ntime, however your property, their equipment and everyone’s safety\r\nis our main priority. \r\n\r\n\r\n<br></p>'),
(2, 'Can I pause, reschedule, or cancel my recurring service?', '<p>Certainly!\r\nPlease provide us a 24 hr notice so that we can notify the service\r\nprovider of the change. \r\n\r\n\r\n<br></p>'),
(2, 'Does Seazoned service street parking, parking lots, alleyways, sidewalks, etc?', '<p>Seazoned\r\ndoes not currently cover street parking, alley ways, parking lots,\r\nsidewalks, etc at this time. Please keep this in mind when placing\r\nyour order.\r\n\r\n<br></p>'),
(2, 'Is Seazoned available in my area?', '<p>\r\n\r\n\r\n	\r\n	\r\n	\r\n	\r\n	</p><p>Enter\r\nyour address to see if we have any providers in your area. If no\r\nproviders are shown, please contact us so that we can look into\r\nfinding providers to service your area. \r\n</p>\r\n\r\n<br><p></p>'),
(2, 'If I like a provider, can I select them for later and additional jobs?', '<p>If\r\nyou like a provider, we recommend that you give them a great\r\nreview/rating and add them to your favorites for future booking.\r\n\r\n<br></p>'),
(2, 'If I’m not home, how will I know my job is completed?', '<p>Once\r\nthe provider has completed a job, the provider will take a picture\r\nwhich will be submitted and sent to you via job complete\r\nnotification.\r\n\r\n<br></p>'),
(2, 'How long will it take a provider to get to my house?', '<p>The\r\nservice will be completed by end of day on the day the job was\r\nscheduled. If you would like your service to be done at specific\r\ntime, please contact provider via messaging in our app.\r\n\r\n<br></p>'),
(2, 'Can I cancel a service once an order has been placed?', '<p>Yes,\r\nbut a cancellation fee will be applied if the job has already been\r\naccepted by the  provider and you have already given payment. If the\r\njob hasn’t been claimed yet, there won’t be any charge.\r\n\r\n<br></p>'),
(2, 'How are providers chosen/evaluated?', '<p>	\r\n\r\n\r\n</p><p>Currently\r\nwe allow freelance providers in order to keep prices lower and\r\ncompetitive . We recommend that our customers read, rate and evaluate\r\nreviews. We highly recommend that our providers get/have liability\r\ninsurance. We advice you to book a provider at your own risk after\r\nreading reviews and ratings given by other users based off of jobs\r\ndone on our site.</p>\r\n\r\n<br><p></p>'),
(2, 'When and how will I be charged?', '<p>When\r\nyou book a service and the provider accepts the request, you are then\r\nrequired to pay for the service. “You will be refunded if the job\r\nis not completed within the time frame.”\r\n\r\n<br></p>'),
(3, 'How do I sign up?', '<p>To\r\nenroll, please register through our Website or Download our\r\nLandscaper App in both the Google Play and iTunes App store for both\r\nAndroid and IOS. If you have questions, please contact us and we can\r\nhelp set up your account. \r\n\r\n\r\n<br></p>'),
(3, 'What requirements are there for signing up as a Seazoned provider? ', '<p>\r\n\r\n\r\n	\r\n	\r\n	\r\n	\r\n	</p><p>We\r\nrequire all of our Seazoned professionals to have the following:</p>\r\n<ul>\r\n	<li><p>Appropriate\r\n	equipment.</p>\r\n	</li><li><p>Iphone\r\n	or Android Phone.</p>\r\n	</li><li><p>Great\r\n	work ethic.</p>\r\n	</li><li><p>Potential\r\n	to make significant income.</p>\r\n</li></ul>\r\n\r\n<br><p></p>'),
(3, 'Can I sign up to offer multiple services?', '<p>Yes!\r\nBeing a Seazoned pro allows you to provide any or all of the services\r\nwe provide on our site.&nbsp;</p><p>*Note,\r\nOur customers property, your equipment along with the safety of all\r\nparties is most important to us. If you are not licensed, skilled or\r\nequipped to perform a service we offer on our site, do not register\r\nyourself for that service. You will be liable for any injuries or\r\ndamages that may occur.\r\n\r\n<br></p>'),
(3, 'How do I begin accepting jobs? ', '<p><br>\r\n</p><ul>\r\n	<li><p>Download\r\n	the app</p>\r\n	</li><li><p>Register\r\n	and enter service information</p>\r\n	</li><li><p>Log\r\n	into, or create a new PayPal account.</p>\r\n	</li><li><p>Via\r\n	the Dashboard, review job details and accept job</p>\r\n</li></ul>\r\n<p><br>\r\n</p>\r\n<p>*Once\r\nyou have accepted a service request, it will be moved to “Pending\r\nJobs” where no one else can claim or see it. Pending jobs are\r\ncategorized by “service type” not “service date.” So keep an\r\neye on the dates of jobs and make sure not to forget about them. \r\n</p>\r\n\r\n<br><p></p>'),
(3, 'How long do I have to complete a job? ', '<p>\r\n\r\n\r\n	\r\n	\r\n	\r\n	\r\n	</p><p>When\r\na customer requests a service, he/she selects a date and time that\r\nworks best for them. We understand that the time may not work with\r\nyour busy schedule, so you have until the end of that day to complete\r\nthe job. <br><br>\r\n</p>\r\n<p>\r\n*Note\r\nall accepted jobs must be complete on request date. In the event of\r\ninclement weather, please contact us so we may notify the customer.</p>\r\n\r\n<br><p></p>'),
(3, 'How do I learn about jobs in my area?', '<p>When\r\na customer in your area requests your service, you will be notified\r\nby notification via Landscaper app. Service details will be shown on\r\nthe app dashboard/home page. Having great reviews will help you to\r\ngain more jobs so make sure to do every job to the best of your\r\nability.\r\n</p><p>\r\n**Note\r\nthat the jobs you see are based on the mileage radius that you\r\nspecify during sign up. You can change your radius anytime in your\r\nprofile service settings.</p>\r\n\r\n<br><p></p>'),
(3, 'Why am I not seeing any available jobs? Please ask yourself the following questions.', '<p><br>\r\n</p><ol>\r\n	<li><p>\r\n	Do\r\n	I need to adjust my pricing?</p>\r\n	</li><li><p>\r\n	Is\r\n	my service area too small?</p>\r\n	</li><li><p>\r\n	Do\r\n	I need to change my hours of operation?</p>\r\n	</li><li><p>\r\n	My\r\n	phone may need to be reset?</p>\r\n	</li><li><p>\r\n	Are\r\n	my reviews in good standing?</p>\r\n</li></ol>\r\n<p>\r\n*Note,\r\nplease contact us and we will try to help you improve your available\r\njobs.</p>\r\n\r\n<br><p></p>'),
(3, 'How do I get paid? ', '<p>One\r\nof the very first things you need to do is log into or create a new\r\nPayPal account. If you do not do this, you will not be able to\r\ncomplete any jobs and will not get paid. \r\n\r\n\r\n<br></p>'),
(3, 'Where do I download the provider app? ', '<p>Download\r\nour “Seazoned Landscaper” App, in both the Google Play and iTunes\r\nApp store for both Android and IOS. If you have questions, please\r\ncontact us and we can help set up your account. \r\n\r\n\r\n<br></p>'),
(3, 'What do I do if a customer’s lawn or driveway doesn’t match the description? ', '<p>Our\r\ncustomers our typically honest in their descriptions. However, in the\r\nevent that the customers  description does not correctly represent\r\nthe job being serviced please take a picture and contact us. If you\r\nfeel that it has been misrepresented, please take a picture of the\r\narea being serviced and contact us. We’ll then reach out to the\r\ncustomer and coordinate a price adjustment if needed. \r\n\r\n\r\n<br></p>');
